name: Deploy QA

on:
  push:
    branches:
      - release/*

env:
  REACT_APP_API_URL: https://funfunz-qa.herokuapp.com
  PUBLIC_URL: /backoffice-qa/
  GH_PAT: ${{ secrets.GH_PAT }}
  GH_USER: ${{ secrets.GH_USER }}
  GH_EMAIL: ${{ secrets.GH_EMAIL }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
    - run: npm run build
    - run: touch build/.nojekyll
    - name: Deploy
      run: |
        cd build/
        git config --global user.name "$GH_USER"
        git config --global user.email "$GH_EMAIL"
        git init
        git checkout -b gh-pages
        git remote add origin https://$GH_USER:$GH_PAT@github.com/Funfunz/backoffice-qa.git
        git add .
        git commit -m 'gh-pages'
        git push -f -u origin gh-pages